export const products = [
    {
        id: 1,
        name: "RADEON RX 6600",
        category: "graphic",
        img: "/img/1.png",
        price: 11620000,
    },
    {
        id: 2,
        name: "ASUS TUF Geforce 16660 Super",
        category: "graphic",
        img: "/img/2.png",
        price: 3659000,
    },
    {
        id: 3,
        name: "MSI Geforce RTX 2060 VENTUS GP OC",
        category: "graphic",
        img: "/img/3.png",
        price: 4749000,
    },
    {
        id: 4,
        name: "MSI Radeon RX 6500",
        category: "graphics",
        img: "/img/4.png",
        price: 2600000,
    },
    {
        id: 5,
        name: "INTEL CORE i9 12900",
        category: "cpu",
        img: "/img/5.png",
        price: 8249000,
    },
    {
        id: 6,
        name: "INTEL CORE i5 12600",
        category: "cpu",
        img: "/img/6.png",
        price: 3989000,
    },
    {
        id: 7,
        name: "INTEL CORE i9 12900KF",
        category: "cpu",
        img: "/img/7.png",
        price: 9929000,
    },
    {
        id: 8,
        name: "INTEL CORE i3 12100",
        category: "cpu",
        img: "/img/8.png",
        price: 2179000,
    },
    {
        id: 9,
        name: "ASROCK WRX80",
        category: "motherboard",
        img: "/img/9.png",
        price: 16499000,
    },
    {
        id: 10,
        name: "ASUS ROG STRIX",
        category: "motherboard",
        img: "/img/10.png",
        price: 4209000,
    },
]